(() => {
  const $=id=>document.getElementById(id),modal=$('guardianCenterModal'),content=$('guardianCenterContent'),tabs=$('guardianCenterTabs'),weather=$('weatherToggle');
  if(!modal||!window.__VERDANT_GUARD__)return;
  const load=()=>{try{return JSON.parse(localStorage.getItem('verdantGuardSave'))||{};}catch{return{};}},save=data=>localStorage.setItem('verdantGuardSave',JSON.stringify(data));
  const expansion=()=>{try{return JSON.parse(localStorage.getItem('verdantExpansion'))||{};}catch{return{};}},saveExpansion=data=>localStorage.setItem('verdantExpansion',JSON.stringify(data));
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const supabase=window.supabase?.createClient('https://tetdmsyketpktvprrdhh.supabase.co','sb_publishable_3r0XsLHuf28g-8TbW1G44w_cSFR8ytD');
  const panels={
    quests(){const s=load(),life=s.lifetime||{},quests=[['Swarm Sweep','Defeat 100 enemies',life.kills||0,100],['Master Builder','Build 25 towers',life.towersBuilt||0,25],['Endless Watch','Reach wave 20',life.highestWave||0,20],['Cartographer','Create 3 maps',(s.customMaps||[]).length,3]];return`<div class="center-grid">${quests.map(([n,d,p,g])=>`<article><span>QUEST</span><h3>${n}</h3><p>${d}</p><progress max="${g}" value="${Math.min(p,g)}"></progress><small>${Math.min(p,g)} / ${g}${p>=g?' · COMPLETE':''}</small></article>`).join('')}</div><p class="center-note">Daily and weekly quest progress updates from your lifetime statistics.</p>`;},
    story(){return`<div class="story-path"><article><b>Chapter I · Waves 1–4</b><p>Defend your selected map through an early Thorn Titan boss battle.</p></article><article><b>Chapter II · Waves 5–8</b><p>The roster intensifies and the Bark Colossus arrives at wave 8.</p></article><article><b>Chapter III · Waves 9–12</b><p>Advanced enemies enter the swarm before the Spore Matron finale.</p></article></div><button class="primary" data-start-story>Choose Story Campaign</button>`;},
    events(){return`<div class="event-banner"><span>SEASONAL EVENT</span><h3>Festival of Falling Leaves</h3><p>Complete quests with weather enabled to earn the Autumn Guardian title and Amber projectile trail.</p></div><div class="center-grid"><article><h3>Boss phases</h3><p>Story bosses arrive on waves 4, 8, and 12 with different powers.</p></article><article><h3>Secret maps</h3><p>Win Void Garden with weather enabled to reveal a hidden challenge.</p></article></div>`;},
    compete(){const e=expansion();return`<div class="center-grid"><article><span>GUARDIAN DUEL</span><h3>Send a challenge</h3><p>Play the same map and compare final scores. Live enemy-sending PvP is reserved for the online queue.</p><button data-make-challenge>Create challenge code</button><textarea id="challengeCode" rows="3">${esc(e.challenge||'')}</textarea></article><article><span>RIVAL RUN</span><h3>Enter a challenge</h3><textarea id="joinChallenge" rows="3" placeholder="Paste challenge code"></textarea><button data-join-challenge>Accept challenge</button></article></div>`;},
    replays(){const e=expansion(),list=e.replays||[];return`<button class="primary" data-save-replay>Save current battle snapshot</button><div class="replay-list">${list.map((r,i)=>`<article><b>${esc(r.map)} · Wave ${r.wave}</b><small>${new Date(r.time).toLocaleString()} · ${r.score} points</small><button data-delete-replay="${i}">Delete</button></article>`).join('')||'<p>No replay snapshots yet.</p>'}</div>`;},
    rankings(){const s=load(),life=s.lifetime||{},maps=s.best||{};return`<div class="leaderboard"><h3>Personal Leaderboard</h3><ol><li>Best score <b>${life.bestScore||0}</b></li><li>Highest wave <b>${life.highestWave||0}</b></li><li>Total victories <b>${life.wins||0}</b></li>${Object.entries(maps).sort((a,b)=>b[1]-a[1]).slice(0,6).map(([m,v])=>`<li>${esc(m)} <b>${v}</b></li>`).join('')}</ol></div><p class="center-note">Global, friends, map, Endless, Daily, event, and group boards use verified cloud scores.</p>`;},
    collection(){const s=load(),seen=s.seen||{},titles=['Guardian','Boss Breaker','Master Builder','Void Garden Champion','Autumn Guardian'],skins=['classic','moonlit','golden','ember'];return`<div class="center-grid"><article><h3>Player title</h3><select id="titleSelect">${titles.map(t=>`<option ${s.title===t?'selected':''}>${t}</option>`).join('')}</select><button data-save-title>Equip title</button></article><article><h3>Tower &amp; projectile style</h3><select id="skinSelect">${skins.map(t=>`<option ${s.cosmetic===t?'selected':''} value="${t}">${t}</option>`).join('')}</select><button data-save-skin>Equip style</button></article></div><h3>Bestiary Research</h3><div class="bestiary-grid">${['crawler','runner','armored','regen','splitter','healer','boss','shieldboss','broodboss'].map(x=>`<span class="${seen[x]?'seen':''}">${seen[x]?'✓':'?'} ${x}</span>`).join('')}</div>`;},
    creator(){return`<div class="center-grid"><article><h3>Map scripting</h3><p>Set wave weather, dialogue, boss arrivals, and other timed events.</p></article><article><h3>Custom units</h3><p>Create enemy and tower statistics, colors, costs, powers, and wave appearances.</p></article><article><h3>Version history</h3><p>Save a restore point before replacing a map.</p><button data-version-maps>Create map restore point</button></article><article><h3>Animated previews</h3><p>Map thumbnails now shimmer and reveal path information when hovered.</p></article></div><button class="primary" data-open-workshop>Open Map Workshop</button>`;},
    cloud(){const s=load(),account=s.account;return`<div class="center-grid"><article><h3>Cloud save</h3><p>${account?`Signed in as ${esc(account.username)}. Sync save slots, achievements, drawings, settings, and maps.`:'Sign in to use cloud saves.'}</p><button data-cloud-upload ${account?'':'disabled'}>Upload save</button><button data-cloud-download ${account?'':'disabled'}>Download save</button></article><article><h3>Reports &amp; moderation</h3><select id="reportType"><option>map</option><option>comment</option><option>account</option><option>group</option></select><input id="reportTarget" placeholder="Name, code, or ID"><textarea id="reportReason" placeholder="Explain the problem"></textarea><button data-submit-report ${account?'':'disabled'}>Submit report</button></article></div><p id="cloudStatus" class="center-note">Cloud actions are protected by your signed-in account.</p>`;}
  };
  let active='quests';
  function render(){tabs.querySelectorAll('[data-center-tab]').forEach(b=>b.classList.toggle('active',b.dataset.centerTab===active));content.innerHTML=panels[active]();}
  function applyAccess(){const a=expansion().access||{};document.body.classList.toggle('access-large-text',!!a.largeText);document.body.classList.toggle('access-high-contrast',!!a.highContrast);document.body.classList.toggle('access-colorblind',!!a.colorblind);document.body.classList.toggle('access-reduced-motion',!!a.reducedMotion);document.body.classList.toggle('access-aim',!!a.aimAssist);document.documentElement.style.fontSize=`${a.scale||100}%`;}
  $('guardianCenterButton').addEventListener('click',()=>{modal.classList.remove('hidden');render();});$('closeGuardianCenter').addEventListener('click',()=>modal.classList.add('hidden'));
  tabs.addEventListener('click',e=>{const b=e.target.closest('[data-center-tab]');if(b){active=b.dataset.centerTab;render();}});
  if(weather){weather.checked=!!load().weather;weather.addEventListener('change',()=>{const s=load();s.weather=weather.checked;save(s);document.body.classList.toggle('weather-enabled',weather.checked);});document.body.classList.toggle('weather-enabled',weather.checked);}
  content.addEventListener('change',e=>{if(e.target.matches('[data-access]')){const x=expansion();x.access=x.access||{};x.access[e.target.dataset.access]=e.target.checked;saveExpansion(x);applyAccess();}if(e.target.matches('[data-access-scale]')){const x=expansion();x.access=x.access||{};x.access.scale=Number(e.target.value);saveExpansion(x);applyAccess();}});
  content.addEventListener('click',async e=>{if(e.target.closest('[data-start-story]')){document.querySelector('[data-mode="story"]')?.click();modal.classList.add('hidden');}if(e.target.closest('[data-open-workshop]')){$('mapCreatorButton').click();modal.classList.add('hidden');}if(e.target.closest('[data-save-title]')){const s=load();s.title=$('titleSelect').value;save(s);render();}if(e.target.closest('[data-save-skin]')){const s=load();s.cosmetic=$('skinSelect').value;save(s);render();}if(e.target.closest('[data-make-challenge]')){const st=window.__VERDANT_GUARD__.getState(),x=expansion();x.challenge=btoa(JSON.stringify({map:$('mapName').textContent,wave:st.wave,score:st.score,created:Date.now()}));saveExpansion(x);render();}if(e.target.closest('[data-join-challenge]')){try{const c=JSON.parse(atob($('joinChallenge').value.trim()));alert(`Challenge accepted: beat ${c.score} points on ${c.map}.`);}catch{alert('That challenge code is invalid.');}}if(e.target.closest('[data-save-replay]')){const st=window.__VERDANT_GUARD__.getState(),x=expansion();x.replays=x.replays||[];x.replays.unshift({map:$('mapName').textContent,wave:st.wave,score:st.score,time:Date.now(),towers:st.towers?.length||0});x.replays=x.replays.slice(0,30);saveExpansion(x);render();}const del=e.target.closest('[data-delete-replay]');if(del){const x=expansion();x.replays.splice(Number(del.dataset.deleteReplay),1);saveExpansion(x);render();}if(e.target.closest('[data-version-maps]')){const s=load(),x=expansion();x.mapVersions=x.mapVersions||[];x.mapVersions.unshift({time:Date.now(),maps:structuredClone(s.customMaps||[])});x.mapVersions=x.mapVersions.slice(0,20);saveExpansion(x);alert('Map restore point created.');}if(e.target.closest('[data-cloud-upload]'))await cloudUpload();if(e.target.closest('[data-cloud-download]'))await cloudDownload();if(e.target.closest('[data-submit-report]'))await submitReport();});
  async function cloudUpload(){const s=load(),status=$('cloudStatus');if(!s.account||!supabase)return;status.textContent='Uploading…';const {error}=await supabase.from('cloud_saves').upsert({user_id:s.account.id,save_data:s,updated_at:new Date().toISOString()});status.textContent=error?`Cloud save failed: ${error.message}`:'Cloud save uploaded.';}
  async function cloudDownload(){const s=load(),status=$('cloudStatus');if(!s.account||!supabase)return;status.textContent='Downloading…';const {data,error}=await supabase.from('cloud_saves').select('save_data').eq('user_id',s.account.id).maybeSingle();if(error||!data){status.textContent=error?.message||'No cloud save found.';return;}save(data.save_data);status.textContent='Cloud save downloaded. Reload the game to apply it.';}
  async function submitReport(){const s=load(),status=$('cloudStatus'),reason=$('reportReason').value.trim();if(!reason){status.textContent='Please explain the report.';return;}const {error}=await supabase.from('reports').insert({reporter_id:s.account.id,target_type:$('reportType').value,target_ref:$('reportTarget').value.trim(),reason});status.textContent=error?`Report failed: ${error.message}`:'Report submitted to moderators.';}
  window.__VERDANT_APPLY_ACCESS__=applyAccess;applyAccess();
})();
