-- Verdant Guard social, moderation, and owner security setup.
-- Run once in Supabase SQL Editor as the project owner.
create extension if not exists citext;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username citext not null unique,
  display_name text not null,
  bio text not null default '' check (char_length(bio)<=300),
  guardian_level integer not null default 1 check (guardian_level>=1),
  role text not null default 'player' check (role in ('player','admin','owner')),
  friend_requests_enabled boolean not null default false,
  cheats_enabled boolean not null default false,
  banned_until timestamptz,
  created_at timestamptz not null default now()
);

-- Usernames are case-insensitively unique from the moment signup begins.
-- Checking auth.users as well as profiles also covers accounts awaiting email confirmation.
create or replace function public.username_available(p_username text)
returns boolean language sql stable security definer set search_path=public,auth as $$
  select char_length(trim(p_username)) between 3 and 30
    and not exists(select 1 from public.profiles where username=trim(p_username)::citext)
    and not exists(select 1 from auth.users where lower(raw_user_meta_data->>'username')=lower(trim(p_username)));
$$;

create or replace function public.reject_duplicate_auth_username()
returns trigger language plpgsql security definer set search_path=public,auth as $$
declare requested text:=trim(new.raw_user_meta_data->>'username');
begin
  if requested is null or char_length(requested) not between 3 and 30 then
    raise exception 'Username must contain 3 to 30 characters';
  end if;
  if exists(select 1 from auth.users where id<>new.id and lower(raw_user_meta_data->>'username')=lower(requested))
     or exists(select 1 from public.profiles where username=requested::citext) then
    raise exception 'Username already taken';
  end if;
  return new;
end $$;

drop trigger if exists reject_duplicate_username_before_signup on auth.users;
create trigger reject_duplicate_username_before_signup before insert on auth.users
for each row execute function public.reject_duplicate_auth_username();

create or replace function public.create_signup_profile()
returns trigger language plpgsql security definer set search_path=public as $$
declare requested text:=trim(new.raw_user_meta_data->>'username');
begin
  insert into public.profiles(id,username,display_name)
  values(new.id,requested,coalesce(nullif(trim(new.raw_user_meta_data->>'display_name'),''),requested));
  return new;
end $$;

drop trigger if exists create_profile_after_signup on auth.users;
create trigger create_profile_after_signup after insert on auth.users
for each row execute function public.create_signup_profile();

-- Repair older confirmed or unconfirmed accounts that were created before the trigger existed.
insert into public.profiles(id,username,display_name)
select u.id,
       trim(u.raw_user_meta_data->>'username')::citext,
       coalesce(nullif(trim(u.raw_user_meta_data->>'display_name'),''),trim(u.raw_user_meta_data->>'username'))
from auth.users u
where char_length(trim(u.raw_user_meta_data->>'username')) between 3 and 30
on conflict do nothing;

create table if not exists public.friendships (
  id bigint generated by default as identity primary key,
  requester_id uuid not null references public.profiles(id) on delete cascade,
  addressee_id uuid not null references public.profiles(id) on delete cascade,
  status text not null default 'pending' check (status in ('pending','accepted')),
  created_at timestamptz not null default now(),
  check (requester_id <> addressee_id)
);
create unique index if not exists friendships_pair_unique on public.friendships
  (least(requester_id,addressee_id), greatest(requester_id,addressee_id));

create table if not exists public.direct_messages (
  id bigint generated by default as identity primary key,
  sender_id uuid not null references public.profiles(id) on delete cascade,
  receiver_id uuid not null references public.profiles(id) on delete cascade,
  body text not null check (char_length(body) between 1 and 500),
  created_at timestamptz not null default now(),
  read_at timestamptz,
  check (sender_id <> receiver_id)
);

create table if not exists public.blocks (
  blocker_id uuid not null references public.profiles(id) on delete cascade,
  blocked_id uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key(blocker_id,blocked_id),
  check(blocker_id<>blocked_id)
);

create table if not exists public.custom_maps (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null references public.profiles(id) on delete cascade,
  name text not null,
  description text not null default '',
  difficulty text not null default 'Unrated',
  visibility text not null default 'private' check (visibility in ('private','code','friends','public')),
  collaboration_mode text not null default 'owner' check (collaboration_mode in ('owner','friends','specific')),
  share_code citext unique,
  map_data jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.map_collaborators (
  map_id uuid not null references public.custom_maps(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key(map_id,user_id)
);

create table if not exists public.groups (
  id uuid primary key default gen_random_uuid(),
  name citext not null unique,
  description text not null check(char_length(description) between 1 and 400),
  owner_id uuid not null references public.profiles(id),
  join_mode text not null default 'open' check(join_mode in ('open','approval')),
  member_count integer not null default 1,
  created_at timestamptz not null default now()
);
create table if not exists public.group_members (
  group_id uuid not null references public.groups(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  role text not null default 'member' check(role in ('member','owner')),
  status text not null default 'accepted' check(status in ('pending','accepted')),
  joined_at timestamptz not null default now(),
  primary key(group_id,user_id)
);
create table if not exists public.group_rooms (
  id uuid primary key default gen_random_uuid(),
  group_id uuid not null references public.groups(id) on delete cascade,
  name text not null,
  visibility text not null default 'members' check(visibility in ('members','public')),
  created_by uuid not null references public.profiles(id),
  created_at timestamptz not null default now()
);
create table if not exists public.group_messages (
  id bigint generated by default as identity primary key,
  room_id uuid not null references public.group_rooms(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  body text not null check(char_length(body) between 1 and 500),
  created_at timestamptz not null default now()
);

create or replace function public.is_owner()
returns boolean language sql stable security definer set search_path=public
as $$ select auth.uid() = '49084e6c-317b-4df0-844c-3f16c960e998'::uuid $$;

create or replace function public.are_friends(a uuid,b uuid)
returns boolean language sql stable security definer set search_path=public
as $$ select exists(select 1 from friendships where status='accepted' and ((requester_id=a and addressee_id=b) or (requester_id=b and addressee_id=a))) $$;
create or replace function public.is_group_member(g uuid)
returns boolean language sql stable security definer set search_path=public
as $$ select exists(select 1 from group_members where group_id=g and user_id=auth.uid() and status='accepted') $$;
create or replace function public.is_group_owner(g uuid)
returns boolean language sql stable security definer set search_path=public
as $$ select exists(select 1 from group_members where group_id=g and user_id=auth.uid() and role='owner' and status='accepted') $$;

alter table public.profiles enable row level security;
alter table public.friendships enable row level security;
alter table public.direct_messages enable row level security;
alter table public.custom_maps enable row level security;
alter table public.blocks enable row level security;
alter table public.map_collaborators enable row level security;
alter table public.groups enable row level security;
alter table public.group_members enable row level security;
alter table public.group_rooms enable row level security;
alter table public.group_messages enable row level security;

drop policy if exists profiles_read on public.profiles;
create policy profiles_read on public.profiles for select to authenticated using (true);
drop policy if exists profiles_insert_self on public.profiles;
create policy profiles_insert_self on public.profiles for insert to authenticated with check (id=auth.uid() and role='player' and not cheats_enabled and banned_until is null);
drop policy if exists profiles_update_self on public.profiles;

drop policy if exists friendships_read_participant on public.friendships;
create policy friendships_read_participant on public.friendships for select to authenticated using (auth.uid() in (requester_id,addressee_id));
drop policy if exists friendships_create on public.friendships;
create policy friendships_create on public.friendships for insert to authenticated with check (requester_id=auth.uid() and exists(select 1 from profiles p where p.id=addressee_id and p.friend_requests_enabled));
drop policy if exists friendships_accept on public.friendships;
create policy friendships_accept on public.friendships for update to authenticated using (addressee_id=auth.uid() and status='pending') with check (addressee_id=auth.uid() and status='accepted');
drop policy if exists friendships_remove on public.friendships;
create policy friendships_remove on public.friendships for delete to authenticated using (auth.uid() in (requester_id,addressee_id));

drop policy if exists messages_read on public.direct_messages;
create policy messages_read on public.direct_messages for select to authenticated using (auth.uid() in (sender_id,receiver_id));
drop policy if exists messages_send_friends on public.direct_messages;
create policy messages_send_friends on public.direct_messages for insert to authenticated with check (sender_id=auth.uid() and public.are_friends(sender_id,receiver_id));

drop policy if exists blocks_own on public.blocks;
create policy blocks_own on public.blocks for all to authenticated using (blocker_id=auth.uid()) with check (blocker_id=auth.uid());

drop policy if exists maps_read on public.custom_maps;
create policy maps_read on public.custom_maps for select to authenticated using (owner_id=auth.uid() or visibility='public' or (visibility='friends' and public.are_friends(owner_id,auth.uid())) or visibility='code');
drop policy if exists maps_write_own on public.custom_maps;
create policy maps_write_own on public.custom_maps for all to authenticated using (owner_id=auth.uid()) with check (owner_id=auth.uid() and (visibility='private' or description ~ '[[:alpha:]]'));
drop policy if exists collaborators_read on public.map_collaborators;
create policy collaborators_read on public.map_collaborators for select to authenticated using (user_id=auth.uid() or exists(select 1 from custom_maps m where m.id=map_id and m.owner_id=auth.uid()));
drop policy if exists collaborators_owner_write on public.map_collaborators;
create policy collaborators_owner_write on public.map_collaborators for all to authenticated using (exists(select 1 from custom_maps m where m.id=map_id and m.owner_id=auth.uid())) with check (exists(select 1 from custom_maps m where m.id=map_id and m.owner_id=auth.uid()));

drop policy if exists groups_read on public.groups;
create policy groups_read on public.groups for select to authenticated using(true);
drop policy if exists groups_create_level20 on public.groups;
create policy groups_create_level20 on public.groups for insert to authenticated with check(owner_id=auth.uid() and exists(select 1 from profiles p where p.id=auth.uid() and p.guardian_level>=20));
drop policy if exists group_members_read on public.group_members;
create policy group_members_read on public.group_members for select to authenticated using(user_id=auth.uid() or public.is_group_member(group_id));
drop policy if exists group_rooms_read on public.group_rooms;
create policy group_rooms_read on public.group_rooms for select to authenticated using(visibility='public' or public.is_group_member(group_id));
drop policy if exists group_rooms_owner_write on public.group_rooms;
create policy group_rooms_owner_write on public.group_rooms for insert to authenticated with check(created_by=auth.uid() and public.is_group_owner(group_id));
drop policy if exists group_messages_read on public.group_messages;
create policy group_messages_read on public.group_messages for select to authenticated using(exists(select 1 from group_rooms r where r.id=room_id and (r.visibility='public' or exists(select 1 from group_members gm where gm.group_id=r.group_id and gm.user_id=auth.uid() and gm.status='accepted'))));
drop policy if exists group_messages_write on public.group_messages;
create policy group_messages_write on public.group_messages for insert to authenticated with check(user_id=auth.uid() and exists(select 1 from group_rooms r join group_members gm on gm.group_id=r.group_id where r.id=room_id and gm.user_id=auth.uid() and gm.status='accepted'));

create or replace function public.owner_manage_user(p_target uuid,p_action text)
returns void language plpgsql security definer set search_path=public as $$
begin
  if not public.is_owner() then raise exception 'Owner access required'; end if;
  if p_target='49084e6c-317b-4df0-844c-3f16c960e998'::uuid then raise exception 'Owner cannot be modified'; end if;
  update profiles set
    banned_until=case when p_action='ban' then now()+interval '100 years' when p_action='pardon' then null else banned_until end,
    cheats_enabled=case when p_action='give_cheats' then true when p_action='remove_cheats' then false else cheats_enabled end,
    role=case when p_action='make_admin' then 'admin' when p_action='remove_admin' then 'player' else role end
  where id=p_target;
end $$;

create or replace function public.owner_rate_map(p_map uuid,p_difficulty text)
returns void language plpgsql security definer set search_path=public as $$
begin
  if not public.is_owner() then raise exception 'Owner access required'; end if;
  if p_difficulty not in ('Super Easy','Easy','Normal','Hard','Extreme','Insane') then raise exception 'Invalid difficulty'; end if;
  update custom_maps set difficulty=p_difficulty,updated_at=now() where id=p_map;
end $$;

create or replace function public.set_friend_requests(p_enabled boolean)
returns void language sql security definer set search_path=public as $$
  update profiles set friend_requests_enabled=p_enabled where id=auth.uid()
$$;

create or replace function public.update_my_profile(p_display_name text,p_bio text)
returns void language plpgsql security definer set search_path=public as $$
begin
  if char_length(trim(p_display_name))<1 or char_length(p_bio)>300 then raise exception 'Invalid profile'; end if;
  update profiles set display_name=left(trim(p_display_name),40),bio=left(p_bio,300) where id=auth.uid();
end $$;

create or replace function public.set_my_guardian_level(p_level integer)
returns void language sql security definer set search_path=public as $$
  update profiles set guardian_level=greatest(guardian_level,least(10000,greatest(1,p_level))) where id=auth.uid()
$$;

create or replace function public.initialize_group()
returns trigger language plpgsql security definer set search_path=public as $$
begin
  insert into group_members(group_id,user_id,role,status) values(new.id,new.owner_id,'owner','accepted') on conflict do nothing;
  insert into group_rooms(group_id,name,visibility,created_by) values(new.id,'general','members',new.owner_id);
  return new;
end $$;
drop trigger if exists initialize_group_after_insert on public.groups;
create trigger initialize_group_after_insert after insert on public.groups for each row execute function public.initialize_group();

create or replace function public.join_group(p_group uuid,p_level integer)
returns void language plpgsql security definer set search_path=public as $$
declare mode text;
begin
  if p_level<5 then raise exception 'Guardian Level 5 required'; end if;
  update profiles set guardian_level=greatest(guardian_level,p_level) where id=auth.uid();
  select join_mode into mode from groups where id=p_group;
  insert into group_members(group_id,user_id,status) values(p_group,auth.uid(),case when mode='open' then 'accepted' else 'pending' end)
  on conflict(group_id,user_id) do nothing;
  if mode='open' then update groups set member_count=(select count(*) from group_members where group_id=p_group and status='accepted') where id=p_group; end if;
end $$;

create or replace function public.leave_group(p_group uuid)
returns void language plpgsql security definer set search_path=public as $$
begin
  if exists(select 1 from group_members where group_id=p_group and user_id=auth.uid() and role='owner') and (select count(*) from group_members where group_id=p_group and role='owner')=1 then raise exception 'Share or transfer ownership before leaving'; end if;
  delete from group_members where group_id=p_group and user_id=auth.uid();
  update groups set member_count=(select count(*) from group_members where group_id=p_group and status='accepted') where id=p_group;
end $$;

create or replace function public.manage_group_owner(p_group uuid,p_target uuid,p_action text)
returns void language plpgsql security definer set search_path=public as $$
begin
  if not exists(select 1 from group_members where group_id=p_group and user_id=auth.uid() and role='owner' and status='accepted') then raise exception 'Group owner required'; end if;
  if p_action='share' then update group_members set role='owner' where group_id=p_group and user_id=p_target and status='accepted';
  elsif p_action='transfer' then update group_members set role='member' where group_id=p_group and user_id=auth.uid(); update group_members set role='owner' where group_id=p_group and user_id=p_target and status='accepted'; update groups set owner_id=p_target where id=p_group;
  elsif p_action='remove' then update group_members set role='member' where group_id=p_group and user_id=p_target;
  else raise exception 'Invalid owner action'; end if;
end $$;

insert into public.profiles(id,username,display_name,role,friend_requests_enabled,guardian_level)
values('49084e6c-317b-4df0-844c-3f16c960e998','TheHeeHa','TheHeeHa','owner',true,100)
on conflict(id) do update set role='owner',username='TheHeeHa',display_name='TheHeeHa',guardian_level=greatest(profiles.guardian_level,100);

insert into public.groups(name,description,owner_id,join_mode)
values('Verdant Guard','The official Verdant Guard community group.','49084e6c-317b-4df0-844c-3f16c960e998','open')
on conflict(name) do update set owner_id=excluded.owner_id;
insert into public.group_members(group_id,user_id,role,status)
select id,'49084e6c-317b-4df0-844c-3f16c960e998','owner','accepted' from public.groups where name='Verdant Guard'
on conflict(group_id,user_id) do update set role='owner',status='accepted';
insert into public.group_rooms(group_id,name,visibility,created_by)
select id,'general','public','49084e6c-317b-4df0-844c-3f16c960e998' from public.groups g where g.name='Verdant Guard' and not exists(select 1 from public.group_rooms r where r.group_id=g.id and r.name='general');

grant execute on function public.owner_manage_user(uuid,text) to authenticated;
grant execute on function public.owner_rate_map(uuid,text) to authenticated;
grant execute on function public.set_friend_requests(boolean) to authenticated;
grant execute on function public.update_my_profile(text,text) to authenticated;
grant execute on function public.set_my_guardian_level(integer) to authenticated;
grant execute on function public.join_group(uuid,integer) to authenticated;
grant execute on function public.leave_group(uuid) to authenticated;
grant execute on function public.manage_group_owner(uuid,uuid,text) to authenticated;
grant execute on function public.username_available(text) to anon,authenticated;
