-- Verdant Guard social, moderation, and owner security setup.
-- Run once in Supabase SQL Editor as the project owner.
create extension if not exists citext;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username citext not null unique,
  display_name text not null,
  bio text not null default '' check (char_length(bio)<=300),
  guardian_level integer not null default 1 check (guardian_level>=1),
  role text not null default 'player' check (role in ('player','admin','owner')),
  friend_requests_enabled boolean not null default false,
  cheats_enabled boolean not null default false,
  banned_until timestamptz,
  created_at timestamptz not null default now()
);

-- A username is taken only when every character matches exactly.
-- Capitalization, digits, punctuation, and spaces all count as differences.
alter table public.profiles alter column username type text using username::text;
drop index if exists public.profiles_username_unique_ci;

-- Usernames are case-insensitively unique from the moment signup begins.
-- Checking auth.users as well as profiles also covers accounts awaiting email confirmation.
create or replace function public.username_available(p_username text)
returns boolean language sql stable security definer set search_path=public,auth as $$
  select char_length(p_username) between 3 and 30
    and p_username ~ '[^[:space:]]'
    and not exists(select 1 from public.profiles where username=p_username)
    and not exists(select 1 from auth.users where raw_user_meta_data->>'username'=p_username);
$$;

-- Supabase password sign-in requires an email internally. The game resolves the
-- exact username first so players only need to enter username + password.
create or replace function public.login_email_for_username(p_username text)
returns text language sql stable security definer set search_path=public,auth as $$
  select u.email
  from public.profiles p
  join auth.users u on u.id=p.id
  where p.username=p_username
  limit 1;
$$;
revoke all on function public.login_email_for_username(text) from public;
grant execute on function public.login_email_for_username(text) to anon,authenticated;

create or replace function public.reject_duplicate_auth_username()
returns trigger language plpgsql security definer set search_path=public,auth as $$
declare requested text:=new.raw_user_meta_data->>'username';
begin
  if requested is null or char_length(requested) not between 3 and 30 or requested !~ '[^[:space:]]' then
    raise exception 'Username must contain 3 to 30 characters';
  end if;
  if exists(select 1 from auth.users where id<>new.id and raw_user_meta_data->>'username'=requested)
     or exists(select 1 from public.profiles where username=requested) then
    raise exception 'Username already taken';
  end if;
  return new;
end $$;

drop trigger if exists reject_duplicate_username_before_signup on auth.users;
create trigger reject_duplicate_username_before_signup before insert on auth.users
for each row execute function public.reject_duplicate_auth_username();

create or replace function public.create_signup_profile()
returns trigger language plpgsql security definer set search_path=public as $$
declare requested text:=new.raw_user_meta_data->>'username';
begin
  insert into public.profiles(id,username,display_name)
  values(new.id,requested,coalesce(nullif(trim(new.raw_user_meta_data->>'display_name'),''),requested));
  return new;
end $$;

drop trigger if exists create_profile_after_signup on auth.users;
create trigger create_profile_after_signup after insert on auth.users
for each row execute function public.create_signup_profile();

-- Repair older confirmed or unconfirmed accounts that were created before the trigger existed.
insert into public.profiles(id,username,display_name)
select u.id,
       u.raw_user_meta_data->>'username',
       coalesce(nullif(u.raw_user_meta_data->>'display_name',''),u.raw_user_meta_data->>'username')
from auth.users u
where char_length(u.raw_user_meta_data->>'username') between 3 and 30
on conflict do nothing;

-- Remove stale public profiles left behind by manually deleted Auth users.
delete from public.profiles p
where not exists(select 1 from auth.users u where u.id=p.id);

create or replace function public.delete_my_account()
returns void language plpgsql security definer set search_path=public,auth as $$
begin
  delete from auth.users where id=auth.uid();
end $$;

create table if not exists public.friendships (
  id bigint generated by default as identity primary key,
  requester_id uuid not null references public.profiles(id) on delete cascade,
  addressee_id uuid not null references public.profiles(id) on delete cascade,
  status text not null default 'pending' check (status in ('pending','accepted')),
  created_at timestamptz not null default now(),
  check (requester_id <> addressee_id)
);
create unique index if not exists friendships_pair_unique on public.friendships
  (least(requester_id,addressee_id), greatest(requester_id,addressee_id));

create table if not exists public.direct_messages (
  id bigint generated by default as identity primary key,
  sender_id uuid not null references public.profiles(id) on delete cascade,
  receiver_id uuid not null references public.profiles(id) on delete cascade,
  body text not null check (char_length(body) between 1 and 500),
  created_at timestamptz not null default now(),
  read_at timestamptz,
  check (sender_id <> receiver_id)
);

create table if not exists public.blocks (
  blocker_id uuid not null references public.profiles(id) on delete cascade,
  blocked_id uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key(blocker_id,blocked_id),
  check(blocker_id<>blocked_id)
);

create table if not exists public.custom_maps (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null references public.profiles(id) on delete cascade,
  name text not null,
  description text not null default '',
  difficulty text not null default 'Unrated',
  visibility text not null default 'private' check (visibility in ('private','code','friends','public')),
  collaboration_mode text not null default 'owner' check (collaboration_mode in ('owner','friends','specific')),
  share_code citext unique,
  map_data jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.map_collaborators (
  map_id uuid not null references public.custom_maps(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key(map_id,user_id)
);

create table if not exists public.groups (
  id uuid primary key default gen_random_uuid(),
  name citext not null unique,
  description text not null check(char_length(description) between 1 and 400),
  owner_id uuid not null references public.profiles(id),
  join_mode text not null default 'open' check(join_mode in ('open','approval')),
  member_count integer not null default 1,
  created_at timestamptz not null default now()
);
create table if not exists public.group_members (
  group_id uuid not null references public.groups(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  role text not null default 'member' check(role in ('member','owner')),
  status text not null default 'accepted' check(status in ('pending','accepted')),
  joined_at timestamptz not null default now(),
  primary key(group_id,user_id)
);
create table if not exists public.group_rooms (
  id uuid primary key default gen_random_uuid(),
  group_id uuid not null references public.groups(id) on delete cascade,
  name text not null,
  visibility text not null default 'members' check(visibility in ('members','public')),
  created_by uuid not null references public.profiles(id),
  created_at timestamptz not null default now()
);
create table if not exists public.group_messages (
  id bigint generated by default as identity primary key,
  room_id uuid not null references public.group_rooms(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  body text not null check(char_length(body) between 1 and 500),
  created_at timestamptz not null default now()
);

create or replace function public.is_owner()
returns boolean language sql stable security definer set search_path=public
as $$ select auth.uid() = '49084e6c-317b-4df0-844c-3f16c960e998'::uuid $$;

create or replace function public.are_friends(a uuid,b uuid)
returns boolean language sql stable security definer set search_path=public
as $$ select exists(select 1 from friendships where status='accepted' and ((requester_id=a and addressee_id=b) or (requester_id=b and addressee_id=a))) $$;
create or replace function public.is_group_member(g uuid)
returns boolean language sql stable security definer set search_path=public
as $$ select exists(select 1 from group_members where group_id=g and user_id=auth.uid() and status='accepted') $$;
create or replace function public.is_group_owner(g uuid)
returns boolean language sql stable security definer set search_path=public
as $$ select exists(select 1 from group_members where group_id=g and user_id=auth.uid() and role='owner' and status='accepted') $$;

alter table public.profiles enable row level security;
alter table public.friendships enable row level security;
alter table public.direct_messages enable row level security;
alter table public.custom_maps enable row level security;
alter table public.blocks enable row level security;
alter table public.map_collaborators enable row level security;
alter table public.groups enable row level security;
alter table public.group_members enable row level security;
alter table public.group_rooms enable row level security;
alter table public.group_messages enable row level security;

drop policy if exists profiles_read on public.profiles;
create policy profiles_read on public.profiles for select to authenticated using (true);
drop policy if exists profiles_insert_self on public.profiles;
create policy profiles_insert_self on public.profiles for insert to authenticated with check (id=auth.uid() and role='player' and not cheats_enabled and banned_until is null);
drop policy if exists profiles_update_self on public.profiles;

drop policy if exists friendships_read_participant on public.friendships;
create policy friendships_read_participant on public.friendships for select to authenticated using (auth.uid() in (requester_id,addressee_id));
drop policy if exists friendships_create on public.friendships;
create policy friendships_create on public.friendships for insert to authenticated with check (requester_id=auth.uid() and exists(select 1 from profiles p where p.id=addressee_id and p.friend_requests_enabled));
drop policy if exists friendships_accept on public.friendships;
create policy friendships_accept on public.friendships for update to authenticated using (addressee_id=auth.uid() and status='pending') with check (addressee_id=auth.uid() and status='accepted');
drop policy if exists friendships_remove on public.friendships;
create policy friendships_remove on public.friendships for delete to authenticated using (auth.uid() in (requester_id,addressee_id));

drop policy if exists messages_read on public.direct_messages;
create policy messages_read on public.direct_messages for select to authenticated using (auth.uid() in (sender_id,receiver_id));
drop policy if exists messages_send_friends on public.direct_messages;
create policy messages_send_friends on public.direct_messages for insert to authenticated with check (sender_id=auth.uid() and public.are_friends(sender_id,receiver_id));

drop policy if exists blocks_own on public.blocks;
create policy blocks_own on public.blocks for all to authenticated using (blocker_id=auth.uid()) with check (blocker_id=auth.uid());

drop policy if exists maps_read on public.custom_maps;
create policy maps_read on public.custom_maps for select to authenticated using (owner_id=auth.uid() or visibility='public' or (visibility='friends' and public.are_friends(owner_id,auth.uid())) or visibility='code');
drop policy if exists maps_write_own on public.custom_maps;
create policy maps_write_own on public.custom_maps for all to authenticated using (owner_id=auth.uid()) with check (owner_id=auth.uid() and (visibility='private' or description ~ '[[:alpha:]]'));
drop policy if exists collaborators_read on public.map_collaborators;
create policy collaborators_read on public.map_collaborators for select to authenticated using (user_id=auth.uid() or exists(select 1 from custom_maps m where m.id=map_id and m.owner_id=auth.uid()));
drop policy if exists collaborators_owner_write on public.map_collaborators;
create policy collaborators_owner_write on public.map_collaborators for all to authenticated using (exists(select 1 from custom_maps m where m.id=map_id and m.owner_id=auth.uid())) with check (exists(select 1 from custom_maps m where m.id=map_id and m.owner_id=auth.uid()));

drop policy if exists groups_read on public.groups;
create policy groups_read on public.groups for select to authenticated using(true);
drop policy if exists groups_create_level20 on public.groups;
create policy groups_create_level20 on public.groups for insert to authenticated with check(owner_id=auth.uid() and exists(select 1 from profiles p where p.id=auth.uid() and p.guardian_level>=20));
drop policy if exists group_members_read on public.group_members;
create policy group_members_read on public.group_members for select to authenticated using(user_id=auth.uid() or public.is_group_member(group_id));
drop policy if exists group_rooms_read on public.group_rooms;
create policy group_rooms_read on public.group_rooms for select to authenticated using(visibility='public' or public.is_group_member(group_id));
drop policy if exists group_rooms_owner_write on public.group_rooms;
create policy group_rooms_owner_write on public.group_rooms for insert to authenticated with check(created_by=auth.uid() and public.is_group_owner(group_id));
drop policy if exists group_messages_read on public.group_messages;
create policy group_messages_read on public.group_messages for select to authenticated using(exists(select 1 from group_rooms r where r.id=room_id and (r.visibility='public' or exists(select 1 from group_members gm where gm.group_id=r.group_id and gm.user_id=auth.uid() and gm.status='accepted'))));
drop policy if exists group_messages_write on public.group_messages;
create policy group_messages_write on public.group_messages for insert to authenticated with check(user_id=auth.uid() and exists(select 1 from group_rooms r join group_members gm on gm.group_id=r.group_id where r.id=room_id and gm.user_id=auth.uid() and gm.status='accepted'));

create or replace function public.owner_manage_user(p_target uuid,p_action text)
returns void language plpgsql security definer set search_path=public as $$
begin
  if not public.is_owner() then raise exception 'Owner access required'; end if;
  if p_target='49084e6c-317b-4df0-844c-3f16c960e998'::uuid then raise exception 'Owner cannot be modified'; end if;
  update profiles set
    banned_until=case when p_action='ban' then now()+interval '100 years' when p_action='pardon' then null else banned_until end,
    cheats_enabled=case when p_action='give_cheats' then true when p_action='remove_cheats' then false else cheats_enabled end,
    role=case when p_action='make_admin' then 'admin' when p_action='remove_admin' then 'player' else role end
  where id=p_target;
end $$;

create or replace function public.owner_rate_map(p_map uuid,p_difficulty text)
returns void language plpgsql security definer set search_path=public as $$
begin
  if not public.is_owner() then raise exception 'Owner access required'; end if;
  if p_difficulty not in ('Super Easy','Easy','Normal','Hard','Extreme','Insane') then raise exception 'Invalid difficulty'; end if;
  update custom_maps set difficulty=p_difficulty,updated_at=now() where id=p_map;
end $$;

create or replace function public.set_friend_requests(p_enabled boolean)
returns void language sql security definer set search_path=public as $$
  update profiles set friend_requests_enabled=p_enabled where id=auth.uid()
$$;

create or replace function public.update_my_profile(p_display_name text,p_bio text)
returns void language plpgsql security definer set search_path=public as $$
begin
  if char_length(trim(p_display_name))<1 or char_length(p_bio)>300 then raise exception 'Invalid profile'; end if;
  update profiles set display_name=left(trim(p_display_name),40),bio=left(p_bio,300) where id=auth.uid();
end $$;

create or replace function public.set_my_guardian_level(p_level integer)
returns void language sql security definer set search_path=public as $$
  update profiles set guardian_level=greatest(guardian_level,least(10000,greatest(1,p_level))) where id=auth.uid()
$$;

create or replace function public.initialize_group()
returns trigger language plpgsql security definer set search_path=public as $$
begin
  insert into group_members(group_id,user_id,role,status) values(new.id,new.owner_id,'owner','accepted') on conflict do nothing;
  insert into group_rooms(group_id,name,visibility,created_by) values(new.id,'general','members',new.owner_id);
  return new;
end $$;
drop trigger if exists initialize_group_after_insert on public.groups;
create trigger initialize_group_after_insert after insert on public.groups for each row execute function public.initialize_group();

create or replace function public.join_group(p_group uuid,p_level integer)
returns void language plpgsql security definer set search_path=public as $$
declare mode text;
begin
  if p_level<5 then raise exception 'Guardian Level 5 required'; end if;
  update profiles set guardian_level=greatest(guardian_level,p_level) where id=auth.uid();
  select join_mode into mode from groups where id=p_group;
  insert into group_members(group_id,user_id,status) values(p_group,auth.uid(),case when mode='open' then 'accepted' else 'pending' end)
  on conflict(group_id,user_id) do nothing;
  if mode='open' then update groups set member_count=(select count(*) from group_members where group_id=p_group and status='accepted') where id=p_group; end if;
end $$;

create or replace function public.leave_group(p_group uuid)
returns void language plpgsql security definer set search_path=public as $$
begin
  if exists(select 1 from group_members where group_id=p_group and user_id=auth.uid() and role='owner') and (select count(*) from group_members where group_id=p_group and role='owner')=1 then raise exception 'Share or transfer ownership before leaving'; end if;
  delete from group_members where group_id=p_group and user_id=auth.uid();
  update groups set member_count=(select count(*) from group_members where group_id=p_group and status='accepted') where id=p_group;
end $$;

create or replace function public.manage_group_owner(p_group uuid,p_target uuid,p_action text)
returns void language plpgsql security definer set search_path=public as $$
begin
  if not exists(select 1 from group_members where group_id=p_group and user_id=auth.uid() and role='owner' and status='accepted') then raise exception 'Group owner required'; end if;
  if p_action='share' then update group_members set role='owner' where group_id=p_group and user_id=p_target and status='accepted';
  elsif p_action='transfer' then update group_members set role='member' where group_id=p_group and user_id=auth.uid(); update group_members set role='owner' where group_id=p_group and user_id=p_target and status='accepted'; update groups set owner_id=p_target where id=p_group;
  elsif p_action='remove' then update group_members set role='member' where group_id=p_group and user_id=p_target;
  else raise exception 'Invalid owner action'; end if;
end $$;

insert into public.profiles(id,username,display_name,role,friend_requests_enabled,guardian_level)
values('49084e6c-317b-4df0-844c-3f16c960e998','TheHeeHa','TheHeeHa','owner',true,100)
on conflict(id) do update set role='owner',username='TheHeeHa',display_name='TheHeeHa',guardian_level=greatest(profiles.guardian_level,100);

insert into public.groups(name,description,owner_id,join_mode)
values('Verdant Guard','The official Verdant Guard community group.','49084e6c-317b-4df0-844c-3f16c960e998','open')
on conflict(name) do update set owner_id=excluded.owner_id;
insert into public.group_members(group_id,user_id,role,status)
select id,'49084e6c-317b-4df0-844c-3f16c960e998','owner','accepted' from public.groups where name='Verdant Guard'
on conflict(group_id,user_id) do update set role='owner',status='accepted';
insert into public.group_rooms(group_id,name,visibility,created_by)
select id,'general','public','49084e6c-317b-4df0-844c-3f16c960e998' from public.groups g where g.name='Verdant Guard' and not exists(select 1 from public.group_rooms r where r.group_id=g.id and r.name='general');

create table if not exists public.cloud_saves(user_id uuid primary key references public.profiles(id) on delete cascade,save_data jsonb not null default '{}'::jsonb,updated_at timestamptz not null default now());
create table if not exists public.reports(id bigint generated by default as identity primary key,reporter_id uuid not null references public.profiles(id) on delete cascade,target_type text not null check(target_type in('map','comment','account','group')),target_ref text not null default '',reason text not null check(char_length(reason) between 1 and 1000),status text not null default 'open',created_at timestamptz not null default now());
create table if not exists public.map_versions(id bigint generated by default as identity primary key,map_id uuid not null references public.custom_maps(id) on delete cascade,owner_id uuid not null references public.profiles(id) on delete cascade,map_data jsonb not null,created_at timestamptz not null default now());
create table if not exists public.verified_scores(id bigint generated by default as identity primary key,user_id uuid not null references public.profiles(id) on delete cascade,board text not null,map_id uuid,score bigint not null,wave integer not null,created_at timestamptz not null default now());
alter table public.cloud_saves enable row level security;alter table public.reports enable row level security;alter table public.map_versions enable row level security;alter table public.verified_scores enable row level security;
drop policy if exists cloud_save_self on public.cloud_saves;create policy cloud_save_self on public.cloud_saves for all to authenticated using(user_id=auth.uid()) with check(user_id=auth.uid());
drop policy if exists reports_create_self on public.reports;create policy reports_create_self on public.reports for insert to authenticated with check(reporter_id=auth.uid());
drop policy if exists versions_owner on public.map_versions;create policy versions_owner on public.map_versions for all to authenticated using(owner_id=auth.uid()) with check(owner_id=auth.uid());
drop policy if exists scores_read on public.verified_scores;create policy scores_read on public.verified_scores for select to authenticated using(true);
drop policy if exists scores_create_self on public.verified_scores;create policy scores_create_self on public.verified_scores for insert to authenticated with check(user_id=auth.uid());

grant execute on function public.owner_manage_user(uuid,text) to authenticated;
grant execute on function public.owner_rate_map(uuid,text) to authenticated;
grant execute on function public.set_friend_requests(boolean) to authenticated;
grant execute on function public.update_my_profile(text,text) to authenticated;
grant execute on function public.set_my_guardian_level(integer) to authenticated;
grant execute on function public.join_group(uuid,integer) to authenticated;
grant execute on function public.leave_group(uuid) to authenticated;
grant execute on function public.manage_group_owner(uuid,uuid,text) to authenticated;
grant execute on function public.username_available(text) to anon,authenticated;
grant execute on function public.delete_my_account() to authenticated;

-- Suggestions, owner-approved feedback reviewers, and cheat-panel audit history.
create table if not exists public.feedback_reviewers (
  user_id uuid primary key references public.profiles(id) on delete cascade,
  granted_by uuid not null references public.profiles(id),
  created_at timestamptz not null default now()
);

create table if not exists public.feedback_entries (
  id bigint generated by default as identity primary key,
  submitter_id uuid references public.profiles(id) on delete set null,
  submitter_name text not null check(char_length(submitter_name) between 1 and 40),
  session_key text not null check(char_length(session_key) between 8 and 100),
  type text not null check(type in ('suggestion','bug','balance','accessibility','other')),
  title text not null check(char_length(title) between 3 and 120),
  message text not null check(char_length(message) between 5 and 2000),
  status text not null default 'open' check(status in ('open','reviewed','planned','closed')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create or replace function public.can_feedback_dm(a uuid,b uuid)
returns boolean language sql stable security definer set search_path=public as $$
  select not exists(
    select 1 from public.blocks
    where (blocker_id=a and blocked_id=b) or (blocker_id=b and blocked_id=a)
  ) and (
    (a='49084e6c-317b-4df0-844c-3f16c960e998'::uuid and exists(
      select 1 from public.feedback_entries where submitter_id=b
    )) or
    (b='49084e6c-317b-4df0-844c-3f16c960e998'::uuid and exists(
      select 1 from public.feedback_entries where submitter_id=a
    ))
  )
$$;

drop policy if exists messages_send_friends on public.direct_messages;
drop policy if exists messages_send_allowed on public.direct_messages;
create policy messages_send_allowed on public.direct_messages for insert to authenticated
with check(sender_id=auth.uid() and (public.are_friends(sender_id,receiver_id) or public.can_feedback_dm(sender_id,receiver_id)));

create table if not exists public.cheat_usage_events (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) on delete set null,
  display_name text not null check(char_length(display_name) between 1 and 40),
  session_key text not null check(char_length(session_key) between 8 and 100),
  surface text not null check(surface in ('home','game')),
  action text not null check(char_length(action) between 1 and 80),
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create or replace function public.can_review_feedback()
returns boolean language sql stable security definer set search_path=public as $$
  select public.is_owner() or exists(
    select 1 from public.feedback_reviewers where user_id=auth.uid()
  )
$$;

create or replace function public.submit_feedback(
  p_type text,
  p_title text,
  p_message text,
  p_display_name text,
  p_session_key text
)
returns bigint language plpgsql security definer set search_path=public as $$
declare
  new_id bigint;
  effective_user uuid;
  effective_name text;
begin
  if p_type not in ('suggestion','bug','balance','accessibility','other') then raise exception 'Invalid feedback type'; end if;
  if char_length(trim(p_title)) not between 3 and 120 then raise exception 'Title must be 3 to 120 characters'; end if;
  if char_length(trim(p_message)) not between 5 and 2000 then raise exception 'Feedback must be 5 to 2000 characters'; end if;
  if char_length(trim(p_session_key)) not between 8 and 100 then raise exception 'Invalid feedback session'; end if;
  select id,display_name into effective_user,effective_name from public.profiles where id=auth.uid();
  effective_name=coalesce(nullif(trim(effective_name),''),nullif(left(trim(p_display_name),40),''),'Guest');
  insert into public.feedback_entries(submitter_id,submitter_name,session_key,type,title,message)
  values(effective_user,effective_name,left(trim(p_session_key),100),p_type,trim(p_title),trim(p_message))
  returning id into new_id;
  return new_id;
end $$;

create or replace function public.set_feedback_status(p_feedback bigint,p_status text)
returns void language plpgsql security definer set search_path=public as $$
begin
  if not public.can_review_feedback() then raise exception 'Feedback reviewer access required'; end if;
  if p_status not in ('open','reviewed','planned','closed') then raise exception 'Invalid feedback status'; end if;
  update public.feedback_entries set status=p_status,updated_at=now() where id=p_feedback;
end $$;

create or replace function public.owner_set_feedback_reviewer(p_username text,p_allowed boolean)
returns void language plpgsql security definer set search_path=public as $$
declare target_id uuid;
begin
  if not public.is_owner() then raise exception 'Owner access required'; end if;
  select id into target_id from public.profiles where username=trim(p_username);
  if target_id is null then raise exception 'Player username not found'; end if;
  if target_id='49084e6c-317b-4df0-844c-3f16c960e998'::uuid then return; end if;
  if p_allowed then
    insert into public.feedback_reviewers(user_id,granted_by) values(target_id,auth.uid())
    on conflict(user_id) do update set granted_by=excluded.granted_by,created_at=now();
  else
    delete from public.feedback_reviewers where user_id=target_id;
  end if;
end $$;

create or replace function public.log_cheat_usage(
  p_surface text,
  p_action text,
  p_display_name text,
  p_session_key text,
  p_details jsonb default '{}'::jsonb
)
returns bigint language plpgsql security definer set search_path=public as $$
declare
  new_id bigint;
  effective_user uuid;
  effective_name text;
begin
  if p_surface not in ('home','game') then raise exception 'Invalid cheat-panel surface'; end if;
  if char_length(trim(p_action)) not between 1 and 80 then raise exception 'Invalid cheat-panel action'; end if;
  if char_length(trim(p_session_key)) not between 8 and 100 then raise exception 'Invalid cheat-panel session'; end if;
  if octet_length(coalesce(p_details,'{}'::jsonb)::text)>4000 then raise exception 'Cheat-panel details are too large'; end if;
  select id,display_name into effective_user,effective_name from public.profiles where id=auth.uid();
  effective_name=coalesce(nullif(trim(effective_name),''),nullif(left(trim(p_display_name),40),''),'Guest');
  insert into public.cheat_usage_events(user_id,display_name,session_key,surface,action,details)
  values(effective_user,effective_name,left(trim(p_session_key),100),p_surface,trim(p_action),coalesce(p_details,'{}'::jsonb))
  returning id into new_id;
  return new_id;
end $$;

alter table public.feedback_reviewers enable row level security;
alter table public.feedback_entries enable row level security;
alter table public.cheat_usage_events enable row level security;

drop policy if exists feedback_reviewers_read on public.feedback_reviewers;
create policy feedback_reviewers_read on public.feedback_reviewers for select to authenticated
using(user_id=auth.uid() or public.is_owner());
drop policy if exists feedback_entries_review on public.feedback_entries;
create policy feedback_entries_review on public.feedback_entries for select to authenticated
using(public.can_review_feedback());
drop policy if exists cheat_usage_owner_read on public.cheat_usage_events;
create policy cheat_usage_owner_read on public.cheat_usage_events for select to authenticated
using(public.is_owner());

revoke insert,update,delete on public.feedback_reviewers from anon,authenticated;
revoke insert,update,delete on public.feedback_entries from anon,authenticated;
revoke insert,update,delete on public.cheat_usage_events from anon,authenticated;
grant select on public.feedback_reviewers to authenticated;
grant select on public.feedback_entries to authenticated;
grant select on public.cheat_usage_events to authenticated;
grant execute on function public.can_review_feedback() to authenticated;
grant execute on function public.submit_feedback(text,text,text,text,text) to anon,authenticated;
grant execute on function public.set_feedback_status(bigint,text) to authenticated;
grant execute on function public.owner_set_feedback_reviewer(text,boolean) to authenticated;
grant execute on function public.log_cheat_usage(text,text,text,text,jsonb) to anon,authenticated;

-- Creator audit sections, internal player notifications, and owner broadcasts.
alter table public.cheat_usage_events drop constraint if exists cheat_usage_events_surface_check;
alter table public.cheat_usage_events add constraint cheat_usage_events_surface_check
  check(surface in ('home','game','creator','failed_password'));

create or replace function public.log_cheat_usage(
  p_surface text,
  p_action text,
  p_display_name text,
  p_session_key text,
  p_details jsonb default '{}'::jsonb
)
returns bigint language plpgsql security definer set search_path=public as $$
declare
  new_id bigint;
  effective_user uuid;
  effective_name text;
begin
  if p_surface not in ('home','game','creator','failed_password') then raise exception 'Invalid cheat-panel surface'; end if;
  if char_length(trim(p_action)) not between 1 and 80 then raise exception 'Invalid cheat-panel action'; end if;
  if char_length(trim(p_session_key)) not between 8 and 100 then raise exception 'Invalid cheat-panel session'; end if;
  if octet_length(coalesce(p_details,'{}'::jsonb)::text)>4000 then raise exception 'Cheat-panel details are too large'; end if;
  select id,display_name into effective_user,effective_name from public.profiles where id=auth.uid();
  effective_name=coalesce(nullif(trim(effective_name),''),nullif(left(trim(p_display_name),40),''),'Guest');
  insert into public.cheat_usage_events(user_id,display_name,session_key,surface,action,details)
  values(effective_user,effective_name,left(trim(p_session_key),100),p_surface,trim(p_action),coalesce(p_details,'{}'::jsonb))
  returning id into new_id;
  return new_id;
end $$;

create table if not exists public.player_notifications (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  type text not null check(type in ('map_rated','made_admin','cheats_given','system')),
  message text not null check(char_length(message) between 1 and 500),
  read boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.owner_broadcasts (
  id bigint generated by default as identity primary key,
  owner_id uuid not null references public.profiles(id),
  scope text not null check(scope in ('global','user','group')),
  target_user uuid references public.profiles(id) on delete cascade,
  target_group uuid references public.groups(id) on delete cascade,
  message text not null check(char_length(message) between 1 and 500),
  font_family text not null default 'Georgia' check(font_family in ('Georgia','Arial','Verdana','monospace')),
  color text not null default '#e8ffd0' check(color ~ '^#[0-9A-Fa-f]{6}$'),
  active boolean not null default true,
  created_at timestamptz not null default now()
);

alter table public.player_notifications enable row level security;
alter table public.owner_broadcasts enable row level security;
drop policy if exists notifications_self_read on public.player_notifications;
create policy notifications_self_read on public.player_notifications for select to authenticated using(user_id=auth.uid());
drop policy if exists notifications_self_update on public.player_notifications;
create policy notifications_self_update on public.player_notifications for update to authenticated using(user_id=auth.uid()) with check(user_id=auth.uid());
drop policy if exists broadcasts_visible on public.owner_broadcasts;
create policy broadcasts_visible on public.owner_broadcasts for select to anon,authenticated using(
  scope='global'
  or target_user=auth.uid()
  or (scope='group' and exists(select 1 from public.group_members gm where gm.group_id=target_group and gm.user_id=auth.uid() and gm.status='accepted'))
  or public.is_owner()
);

create or replace function public.owner_send_broadcast(p_scope text,p_target text,p_message text,p_font text,p_color text)
returns bigint language plpgsql security definer set search_path=public as $$
declare
  new_id bigint;
  user_target uuid;
  group_target uuid;
begin
  if not public.is_owner() then raise exception 'Owner access required'; end if;
  if p_scope not in ('global','user','group') then raise exception 'Invalid message audience'; end if;
  if char_length(trim(p_message)) not between 1 and 500 then raise exception 'Message must be 1 to 500 characters'; end if;
  if p_font not in ('Georgia','Arial','Verdana','monospace') then raise exception 'Invalid font'; end if;
  if p_color !~ '^#[0-9A-Fa-f]{6}$' then raise exception 'Invalid color'; end if;
  if p_scope='user' then
    select id into user_target from public.profiles where lower(username)=lower(trim(p_target));
    if user_target is null then raise exception 'Username not found'; end if;
  elsif p_scope='group' then
    select id into group_target from public.groups where lower(name)=lower(trim(p_target));
    if group_target is null then raise exception 'Group not found'; end if;
  end if;
  insert into public.owner_broadcasts(owner_id,scope,target_user,target_group,message,font_family,color)
  values(auth.uid(),p_scope,user_target,group_target,trim(p_message),p_font,p_color)
  returning id into new_id;
  return new_id;
end $$;

create or replace function public.owner_manage_user(p_target uuid,p_action text)
returns void language plpgsql security definer set search_path=public as $$
begin
  if not public.is_owner() then raise exception 'Owner access required'; end if;
  if p_target='49084e6c-317b-4df0-844c-3f16c960e998'::uuid then raise exception 'Owner cannot be modified'; end if;
  if p_action not in ('ban','pardon','give_cheats','remove_cheats','make_admin','remove_admin') then raise exception 'Invalid owner action'; end if;
  update profiles set
    banned_until=case when p_action='ban' then now()+interval '100 years' when p_action='pardon' then null else banned_until end,
    cheats_enabled=case when p_action='give_cheats' then true when p_action='remove_cheats' then false else cheats_enabled end,
    role=case when p_action='make_admin' then 'admin' when p_action='remove_admin' then 'player' else role end
  where id=p_target;
  if p_action='make_admin' then insert into public.player_notifications(user_id,type,message) values(p_target,'made_admin','You are now a Verdant Guard admin.'); end if;
  if p_action='give_cheats' then insert into public.player_notifications(user_id,type,message) values(p_target,'cheats_given','The owner gave your account cheat-panel access.'); end if;
end $$;

create or replace function public.owner_rate_map(p_map uuid,p_difficulty text)
returns void language plpgsql security definer set search_path=public as $$
declare
  map_owner uuid;
  map_name text;
begin
  if not public.is_owner() then raise exception 'Owner access required'; end if;
  if p_difficulty not in ('Super Easy','Easy','Normal','Hard','Extreme','Insane') then raise exception 'Invalid difficulty'; end if;
  update public.custom_maps set difficulty=p_difficulty,updated_at=now() where id=p_map returning owner_id,name into map_owner,map_name;
  if map_owner is not null then insert into public.player_notifications(user_id,type,message) values(map_owner,'map_rated',format('Your map “%s” was rated %s.',map_name,p_difficulty)); end if;
end $$;

revoke insert,update,delete on public.player_notifications from anon,authenticated;
revoke insert,update,delete on public.owner_broadcasts from anon,authenticated;
grant select on public.player_notifications to authenticated;
grant update(read) on public.player_notifications to authenticated;
grant select on public.owner_broadcasts to anon,authenticated;
grant execute on function public.owner_send_broadcast(text,text,text,text,text) to authenticated;

-- Retain map history for owner review, including visibility and archive/delete status.
alter table public.custom_maps add column if not exists archived_at timestamptz;
alter table public.custom_maps add column if not exists deleted_at timestamptz;

update public.custom_maps
set archived_at=coalesce(archived_at,updated_at)
where coalesce((map_data->>'archived')::boolean,false) and archived_at is null;

update public.custom_maps
set map_data=jsonb_set(
  jsonb_set(coalesce(map_data,'{}'::jsonb),'{archived}',to_jsonb(archived_at is not null),true),
  '{deleted}',to_jsonb(deleted_at is not null),true
);

drop policy if exists maps_read on public.custom_maps;
create policy maps_read on public.custom_maps for select to authenticated using (
  public.is_owner()
  or owner_id=auth.uid()
  or (
    deleted_at is null and archived_at is null and (
      visibility='public'
      or (visibility='friends' and public.are_friends(owner_id,auth.uid()))
      or visibility='code'
    )
  )
);

-- Owner-only map-list organization. This does not change a creator's map visibility.
alter table public.custom_maps add column if not exists owner_archived_at timestamptz;

create or replace function public.owner_set_map_archive(p_map uuid,p_archived boolean)
returns void language plpgsql security definer set search_path=public as $$
begin
  if not public.is_owner() then raise exception 'Owner access required'; end if;
  update public.custom_maps
  set owner_archived_at=case when p_archived then now() else null end
  where id=p_map;
end;
$$;

grant execute on function public.owner_set_map_archive(uuid,boolean) to authenticated;
