const CACHE='verdant-guard-v56';
const CORE=['./','./index.html','./styles.css?v=20260826-23','./expansion.css?v=20260826-23','./game.js?v=20260826-23','./expansion.js?v=20260826-23','./manifest.webmanifest','./icon-192.png','./icon-512.png','./apple-touch-icon.png','./gameplay.png'];
const BACKGROUND_TAG='verdant-notifications';
const DB_NAME='verdant-guard-background';
const STORE_NAME='settings';

function openDatabase(){return new Promise((resolve,reject)=>{const request=indexedDB.open(DB_NAME,1);request.onupgradeneeded=()=>request.result.createObjectStore(STORE_NAME);request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error);});}
async function readSettings(){const database=await openDatabase();return new Promise((resolve,reject)=>{const transaction=database.transaction(STORE_NAME),request=transaction.objectStore(STORE_NAME).get('notifications');request.onsuccess=()=>resolve(request.result||{});request.onerror=()=>reject(request.error);transaction.oncomplete=()=>database.close();});}
async function writeSettings(patch){const current=await readSettings(),next={...current,...patch};if(!patch.lastBroadcastId&&current.lastBroadcastId)next.lastBroadcastId=current.lastBroadcastId;const database=await openDatabase();await new Promise((resolve,reject)=>{const transaction=database.transaction(STORE_NAME,'readwrite');transaction.objectStore(STORE_NAME).put(next,'notifications');transaction.oncomplete=resolve;transaction.onerror=()=>reject(transaction.error);});database.close();return next;}
async function refreshSession(settings){const session=settings.session;if(!session?.refreshToken||!settings.apiUrl||!settings.anonymousKey)return settings;if(Number(session.expiresAt||0)*1000>Date.now()+60000)return settings;try{const response=await fetch(`${settings.apiUrl}/auth/v1/token?grant_type=refresh_token`,{method:'POST',headers:{apikey:settings.anonymousKey,'Content-Type':'application/json'},body:JSON.stringify({refresh_token:session.refreshToken})});if(!response.ok)return settings;const data=await response.json();return writeSettings({session:{accessToken:data.access_token,refreshToken:data.refresh_token||session.refreshToken,expiresAt:data.expires_at,userId:data.user?.id||session.userId}});}catch{return settings;}}
async function apiRows(settings,table,query){const token=settings.session?.accessToken||settings.anonymousKey;if(!settings.apiUrl||!settings.anonymousKey||!token)return[];try{const response=await fetch(`${settings.apiUrl}/rest/v1/${table}?${query}`,{headers:{apikey:settings.anonymousKey,Authorization:`Bearer ${token}`}});return response.ok?await response.json():[];}catch{return[];}}
async function showBackgroundNotification(body,tag){if(!body)return;await self.registration.showNotification('Verdant Guard',{body:String(body).slice(0,240),icon:'./icon-192.png',badge:'./icon-192.png',tag,data:{url:'./'},renotify:true});}
async function checkBackgroundNotifications(){let settings=await readSettings();if(!settings.enabled)return;settings=await refreshSession(settings);const broadcasts=await apiRows(settings,'owner_broadcasts','select=id,message,created_at&active=eq.true&order=created_at.desc&limit=20'),broadcast=broadcasts.find(row=>!String(row.message||'').startsWith('VG_TITLE:')&&Date.now()-new Date(row.created_at).getTime()<=30*60*1000);if(broadcast&&String(broadcast.id)!==String(settings.lastBroadcastId||'')){await showBackgroundNotification(broadcast.message,`verdant-broadcast-${broadcast.id}`);settings=await writeSettings({lastBroadcastId:String(broadcast.id)});}if(settings.session?.userId){const notices=await apiRows(settings,'player_notifications','select=id,message,created_at&read=eq.false&order=created_at.desc&limit=1'),notice=notices[0];if(notice&&String(notice.id)!==String(settings.lastNotificationId||'')){await showBackgroundNotification(notice.message,`verdant-account-${notice.id}`);await writeSettings({lastNotificationId:String(notice.id)});}}}

self.addEventListener('install',event=>event.waitUntil(caches.open(CACHE).then(cache=>cache.addAll(CORE)).then(()=>self.skipWaiting())));
self.addEventListener('activate',event=>event.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(key=>key!==CACHE).map(key=>caches.delete(key)))).then(()=>self.clients.claim())));
self.addEventListener('fetch',event=>{if(event.request.method!=='GET')return;const request=event.request.mode==='navigate'?new Request(event.request,{cache:'reload'}):event.request;event.respondWith(fetch(request).then(response=>{const copy=response.clone();caches.open(CACHE).then(cache=>cache.put(event.request,copy));return response;}).catch(()=>caches.match(event.request).then(hit=>hit||caches.match('./index.html'))));});
self.addEventListener('message',event=>{const data=event.data||{};if(data.type==='SKIP_WAITING')event.waitUntil(self.skipWaiting());if(data.type==='VERDANT_NOTIFICATION_CONFIG')event.waitUntil(writeSettings(data).then(()=>data.enabled?checkBackgroundNotifications():undefined));if(data.type==='VERDANT_BROADCAST_SEEN')event.waitUntil(writeSettings({lastBroadcastId:String(data.id||'')}));});
self.addEventListener('periodicsync',event=>{if(event.tag===BACKGROUND_TAG)event.waitUntil(checkBackgroundNotifications());});
self.addEventListener('push',event=>{let payload={};try{payload=event.data?.json()||{};}catch{payload={body:event.data?.text()||'You have a new Verdant Guard notification.'};}event.waitUntil(showBackgroundNotification(payload.body||payload.message||'You have a new Verdant Guard notification.',payload.tag||'verdant-guard-push'));});
self.addEventListener('notificationclick',event=>{event.notification.close();event.waitUntil(self.clients.matchAll({type:'window',includeUncontrolled:true}).then(windows=>{const open=windows.find(client=>'focus'in client);return open?open.focus():self.clients.openWindow('./');}));});
